[phases.setup]
nixPkgs = ["php82", "composer", "nginx", "php82Extensions.pdo", "php82Extensions.pdo_mysql"]

[phases.build]
cmd = "composer install --no-dev --optimize-autoloader"

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
